# Generated by Django 3.0.5 on 2020-05-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management_portal', '0004_roughsolution_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='content_type',
            field=models.CharField(choices=[('TEXT', 'text'), ('HTML', 'html'), ('MARKDOWN', 'mark_down')], max_length=100),
        ),
        migrations.AlterField(
            model_name='roughsolution',
            name='language',
            field=models.CharField(choices=[('PYTHON', 'PYTHON'), ('C', 'C'), ('CPP', 'CPP'), ('PYTHON36', 'PYTHON36'), ('PYTHON37', 'PYTHON37'), ('PYTHON38', 'PYTHON38'), ('PYTHON38_DATASCIENCE', 'PYTHON38_DATASCIENCE'), ('PYTHON38_AIML', 'PYTHON38_AIML')], max_length=100),
        ),
        migrations.AlterField(
            model_name='roughsolution',
            name='solution_content',
            field=models.TextField(),
        ),
    ]
