# Generated by Django 3.0.5 on 2020-05-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management_portal', '0005_auto_20200529_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content_type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('HTML', 'HTML'), ('MARKDOWN', 'MARKDOWN')], max_length=100),
        ),
    ]
