# Generated by Django 3.0.5 on 2020-06-03 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management_portal', '0011_hint'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionApproach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description_content', models.TextField()),
                ('description_content_type', models.CharField(choices=[('TEXT', 'TEXT'), ('HTML', 'HTML'), ('MARKDOWN', 'MARKDOWN')], max_length=100)),
                ('complexity_analysis_content', models.TextField()),
                ('complexity_analysis_content_type', models.CharField(choices=[('TEXT', 'TEXT'), ('HTML', 'HTML'), ('MARKDOWN', 'MARKDOWN')], max_length=100)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution_approach', to='content_management_portal.Question')),
            ],
        ),
    ]
