# Generated by Django 3.0.5 on 2020-07-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management_portal', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
