# Generated by Django 3.0.5 on 2020-06-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management_portal', '0007_testcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='language',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='solution_content',
        ),
        migrations.AddField(
            model_name='testcase',
            name='input',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_hidden',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='output',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
