# Generated by Django 3.0.5 on 2020-06-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management_portal', '0012_solutionapproach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleansolution',
            name='language',
            field=models.CharField(choices=[('PYTHON', 'PYTHON'), ('C', 'C'), ('CPP', 'CPP'), ('CS', 'CS'), ('JAVASCRIPT', 'JAVASCRIPT'), ('JAVA', 'JAVA'), ('PHP', 'PHP'), ('RUBY', 'RUBY')], max_length=100),
        ),
        migrations.AlterField(
            model_name='prefilledcode',
            name='language',
            field=models.CharField(choices=[('PYTHON', 'PYTHON'), ('C', 'C'), ('CPP', 'CPP'), ('CS', 'CS'), ('JAVASCRIPT', 'JAVASCRIPT'), ('JAVA', 'JAVA'), ('PHP', 'PHP'), ('RUBY', 'RUBY')], max_length=100),
        ),
        migrations.AlterField(
            model_name='roughsolution',
            name='language',
            field=models.CharField(choices=[('PYTHON', 'PYTHON'), ('C', 'C'), ('CPP', 'CPP'), ('CS', 'CS'), ('JAVASCRIPT', 'JAVASCRIPT'), ('JAVA', 'JAVA'), ('PHP', 'PHP'), ('RUBY', 'RUBY')], max_length=100),
        ),
    ]
