# Generated by Django 3.0.5 on 2020-06-13 09:44

import content_management_portal.models.test_case
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management_portal', '0014_auto_20200610_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='score',
            field=models.IntegerField(validators=[content_management_portal.models.test_case.validate_postive]),
        ),
    ]
